[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
http_port = 8069
log_level = info
admin_passwd = $pbkdf2-sha512$600000$x3jv3VvrnVPqPSek9F4rZQ$2H4NqJuN7e2jM/wuuoGkZHIA7PobH4OvhOtj0y9BGSBcoqwsM5tkuVVno80flE0ZAioNUMLX1I8664PznizTOw

